# -*- coding: utf-8 -*-
"""Первичный анализ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gu4Jb0XJroVCuxWRlRO62rnlveHSjRdR

# Порядок выполнения проектной работы
### 1. Сбор и очистка данных
### 2. Анализ данных
### 3. Создание модели
### 4. Оценка качества модели

# <b>Сбор и очистка данных</b>

Парсер находится в файле parser.py и собирает данные с сайта mirkvartir.ru. Соберем 10000 предложений со случайных страниц сайта. Сохраняем в файл main_data10000.csv. Собранные объекты имеют слудующие параметры:

id - идентификатор;<br>
url - ссылка на предложение;<br>
title - заголовок;<br>
price - стоимость аренды за месяц;<br>
laltitude - широта в координатах;<br>
longitude - долгота в координатах;<br>
metro_name - название ближайшей станции метро;<br>
metro_distanse - расстояние до метро в минутах;<br>
distanceType - тип транспорта, на котором можно добраться до метро за указанное  количество минут;<br>
update_time - время последнего обновления предложения.
<br><br>
По ожиданиям, цена аренды должна больше всего зависеть от площади квартиры, расстояния до метро и этажа. Соберем данные и посмотрим зависимости на графиках.
"""

import pandas as pd
import numpy as np
offers = pd.read_csv('../csv_files/main_data10000.csv')
print(len(offers))
offers.head(5)

offers.info()

"""Видим, что из 10000 записей только 7450 имеют заполненное поле metro_name, 7450 - distanceType, 1016 - metro_distance.

На сайте расстояние до метро представлено в неудобном формате времени, к тому же, время может измеряться относительно поездки на транспорте или пешего прохода. Нужно привести данные к единому объективному формату. Поле metro_distance заполнено всего у 1016 строк, но metro_name - у 7450. Лучше самостоятельно посчитать расстояние от квартиры до станции - таким образом сохраним больше данных и приведем их к объективным единицам измерения.

Очистим строки без упоминания станции метро.
"""

def filter_drop_metroname(offers_file: str, output_file: str) -> None:
    """
    функция чистит данные от ненужной информации и строк с пропусками
    :param stations_file: json файл с информацией о станциях метро
    :param offers_file: csv файл с объявлениями
    :param output_file: csv файл вывода данных
    :return: None
    """

    offers = pd.read_csv(offers_file)
    offers = offers.dropna(subset=['metro_name'])

    offers.to_csv(output_file, index=False)
    return None


filter_drop_metroname("../csv_files/main_data10000.csv", '../csv_files/data_filter1.csv')
offers = pd.read_csv('../csv_files/data_filter1.csv')
print(len(offers))

"""Информация о площади, количестве комнат и этаже содержитсяв едином заголовке. Парсим строку и разделяем данные на столбцы."""

def filter_parse_strings(offers_file: str, output_file: str):
    offers = pd.read_csv(offers_file)
    rooms = []
    area = []
    floor = []
    max_floor = []
    for i in range(len(offers)):
        offer = offers.iloc[i]
        room, ar, fl = offer.title.split(', ')
        if room == 'Студия':
            room = 0
        else:
            room = int(room[0])

        ar = float(ar.split()[0])
        if '/' not in fl:
          mx_fl = np.nan
        else:
          mx_fl = int(fl.split()[0].split('/')[1])
        fl = int(fl.split()[0].split('/')[0])
        rooms.append(room)
        area.append(ar)
        floor.append(fl)
        max_floor.append(mx_fl)

    offers['rooms'] = rooms
    offers['area'] = area
    offers['floor'] = floor
    offers['max_floor'] = max_floor
    offers = offers.dropna(subset=['max_floor'])
    offers['max_floor'] = offers['max_floor'].astype(int)
    offers['price_per_sqm'] = offers['price'] / offers['area']
    offers.to_csv(output_file, index=False)

    return None


filter_parse_strings('../csv_files/data_filter1.csv', '../csv_files/data_filter2.csv')
offers = pd.read_csv('../csv_files/data_filter2.csv')
print(len(offers))
offers.head(5)

"""Вычислим расстояние от квартиры до метро в метрах при помощи координат ближайшей станции, найденных в открытом доступе (stations.json)."""

import math
from geopy.distance import geodesic


def add_metro_distance(stations_file: str, offers_file: str, output_file: str) -> None:
    """
    функция добавляет к каждому объявлению расстояние от
    квартиры до метро в координатах
    :param stations_file: json файл с информацией о станциях метро
    :param offers_file: csv файл с объявлениями
    :return: None
    """
    stations = pd.read_json(stations_file)
    offers = pd.read_csv(offers_file)
    metro_distance = []
    for i in range(len(offers)):
        offer = offers.iloc[i]
        if type(offer.metro_name) != float:
            flat_cords = (float(offer.latitude), float(offer.longitude))
            st = stations.loc[stations.Name == offer.metro_name]
            if len(st) == 0:
                metro_distance.append(-1)
                continue
            st = st.iloc[0]
            metro_cords = (float(st.Lat), float(st.Lon))
            metro_distance.append(geodesic((offer.latitude, offer.longitude), metro_cords).meters)
        else:
            metro_distance.append(-1)

    offers["metro_dist"] = metro_distance
    offers.to_csv(output_file, index=False)
    return None


add_metro_distance("../stations.json", "../csv_files/data_filter2.csv", '../csv_files/data_filter3.csv')
offers = pd.read_csv('../csv_files/data_filter3.csv')
offers.head(5)

"""Избавимся от ненужных столбцов и обезличим данные."""

def filter_only_for_training(input_file, output_file):
    offers = pd.read_csv(input_file)

    offers.drop('title', axis=1, inplace=True)
    offers.drop('url', axis=1, inplace=True)
    offers.drop('metro_distance', axis=1, inplace=True)
    offers.drop('distanceType', axis=1, inplace=True)
    offers.drop('update_time', axis=1, inplace=True)
    offers.drop('metro_name', axis=1, inplace=True)

    offers.to_csv(output_file, index=False)
    return None


filter_only_for_training('../csv_files/data_filter3.csv', '../csv_files/data_filter4.csv')
offers = pd.read_csv('../csv_files/data_filter4.csv')
offers.head(5)

"""Сбор данных происходил со случайных страниц, поэтому не исключены дубликаты строк. Найдем и очистим их."""

print(offers.duplicated().sum())
offers = offers.drop_duplicates()
print(offers.duplicated().sum())
print(len(offers))
offers.to_csv('../csv_files/data_filter5.csv', index=False)

"""## <b>Анализ данных</b>

Посмотрим распределение данных и проанализируем выбросы, которые плохо повлияют на модель.
"""

pd.set_option('display.float_format', lambda x: f'{x:.6f}')
offers.describe(percentiles=[.01, .25, .5, .75, .99]).T

"""**1. Ценовые показатели (price):**

Средняя цена 61,321 руб, но есть экстремальные выбросы (макс 1,6 млн руб). 99% цен ниже 300,000 руб, что разумно для аренды. Медиана 45,000 руб показывает правостороннюю асимметрию.

**2. Географические координаты (latitude, longitude):**

Разброс координат соответствует границам СПб. Среднее положение (59.94, 30.33) - центр города. Стандартные отклонения малы (0.071 и 0.087), что говорит о хорошей географической кластеризации данных.

**3. Характеристики жилья:**

rooms: Медиана 1 комната, 75% квартир имеют ≤2 комнаты.

area: Средняя площадь 49.24 м², но в 99% входят и крупные объекты (172.9 м²).

Этажность: медианные значения floor=5 и max_floor=11 типичны для СПб.

**4. Расстояние до метро:**

metro_dist: Медиана 1481 м, но в 99% входит и 14.725 км - явные выбросы.


Экстремальные выбросы в price (1.6 млн).
Широкий разброс в metro_dist (от 83 м до 35.5 км).
Расхождение между средним и медианным price (61,321 vs 45,000) указывает на ненормальное распределение.

<br>

Рынок аренды в основном представлен 1-2 комнатными квартирами (~50 м²).

50% квартир расположены в 1.48 км от метро.

Геоданные показывают хорошее покрытие по всему городу без явных "дыр".

Отфильтруем выбросы:
"""

price_lower = offers['price'].quantile(0.01)
price_upper = offers['price'].quantile(0.99)
metro_max = offers['metro_dist'].quantile(0.99)
max_area = offers['area'].quantile(0.995)

offers_filtered = offers[
    (offers['price'] >= price_lower) &
    (offers['price'] <= price_upper) &
    (offers['metro_dist'] <= metro_max) &
    (offers['area'] <= max_area)
].copy()

print(f"Удалено {len(offers) - len(offers_filtered)} строк (выбросы по цене и расстоянию до метро)")
offers_filtered.to_csv('../csv_files/final_data.csv', index=False)

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
sns.histplot(offers_filtered['price'], bins=30, kde=True, color='skyblue')
plt.title("Распределение цен")
plt.xlabel("Цена, руб")

plt.subplot(1, 2, 2)
sns.boxplot(x=offers_filtered['price'], color='lightgreen')
plt.title("Boxplot цен")
plt.xlabel("Цена, руб")
plt.tight_layout()
plt.show()

"""Распределение цен имеет правостороннюю асимметрию, то есть большинство цен сосредоточено в нижнем диапазоне (около 50,000 руб), а затем резко уменьшается. Наблюдается постепенное уменьшение количества по мере увеличения цен, с редкими высокими значениями. Ящик показывает, что 50% данных лежат в относительно узком диапазоне."""

fig, axes = plt.subplots(2, 2, figsize=(16, 12))

sns.regplot(x='area', y='price', data=offers_filtered,
            scatter_kws={'alpha':0.3}, line_kws={'color':'red'},
            ax=axes[0, 0])
axes[0, 0].set_title("Зависимость цены от площади\nс линией регрессии", pad=10)

room_price = offers_filtered.groupby('rooms')['price'].median().reset_index()
sns.barplot(x='rooms', y='price', data=room_price, ax=axes[0, 1], palette='Blues_d')
axes[0, 1].set_title("Медианная цена по количеству комнат", pad=10)
axes[0, 1].set_ylabel("Медианная цена, руб")

sns.scatterplot(x='metro_dist', y='price', data=offers_filtered,
                alpha=0.3, ax=axes[1, 0])
sns.kdeplot(x='metro_dist', y='price', data=offers_filtered,
            levels=5, color='red', ax=axes[1, 0])
axes[1, 0].set_title("Цена vs Расстояние до метро\nс ядерной оценкой", pad=10)
axes[1, 0].set_xlabel("Расстояние до метро, м")
floor_price = offers_filtered.groupby('floor')['price_per_sqm'].mean().reset_index()
sns.lineplot(x='floor', y='price_per_sqm', data=floor_price,
             marker='o', ax=axes[1, 1], color='green')
axes[1, 1].set_title("Средняя цена за кв.м по этажу", pad=10)
axes[1, 1].set_ylabel("Средняя цена за кв.м, руб")
plt.tight_layout()
plt.show()

"""Наблюдается положительная корреляция между площадью и ценой: с увеличением площади цена также увеличивается. Линия регрессии показывает общую тенденцию роста цен с увеличением площади, хотя есть разброс данных, особенно на больших площадях.

Медианная цена увеличивается с ростом количества комнат. Особенно заметен рост цен на квартиры с 4 и 7 комнатами.

Наибольшая концентрация более дорогих объектов находится вблизи метро (до 2000 м). С увеличением расстояния от метро цены, как правило, снижаются.

Видно, что средняя цена за квадратный метр варьируется в зависимости от этажа. Есть пики на некоторых этажах, что может быть связано с предпочтениями покупателей или особенностями конкретных зданий на этих этажах.
"""

plt.figure(figsize=(12, 8))
sns.scatterplot(
    x='longitude', y='latitude',
    hue='price_per_sqm',
    size='area',
    sizes=(20, 200),
    palette='viridis',
    alpha=0.7,
    data=offers_filtered[offers_filtered['price_per_sqm'] <= offers_filtered['price_per_sqm'].quantile(0.99)]
)
plt.title("Геораспределение цен за кв.м", pad=15)
plt.xlabel("Долгота")
plt.ylabel("Широта")
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

"""Размер точек указывает на площадь объекта. Более крупные точки представляют большие площади. Видно, что более крупные объекты присутствуют в разнообразных ценовых сегментах.

Основная концентрация объектов находится в центральных районах, где наблюдаются более высокие цены. В отдалённых районах цены, как правило, ниже, что видно по преобладанию фиолетовых точек.

Можно заметить концентрацию более дорогих квартир в центре, имеет смыст добавить признак расстояния до центра города, найденного из статистических данных.
"""

from geopy.distance import geodesic


def add_centre_distance(offers_file: str, output_file: str) -> None:
    """
    функция добавляет к каждому объявлению расстояние от
    квартиры до метро в координатах
    :param stations_file: json файл с информацией о станциях метро
    :param offers_file: csv файл с объявлениями
    :return: None
    """
    offers = pd.read_csv(offers_file)
    centre_distance = []
    for i in range(len(offers)):
        offer = offers.iloc[i]
        flat_cords = (float(offer.latitude), float(offer.longitude))
        centre_coords = (59.94, 30.33)
        centre_distance.append(geodesic((offer.latitude, offer.longitude), centre_coords).meters)

    offers['centre_distance'] = centre_distance
    offers.to_csv(output_file, index=False)
    return None


add_centre_distance("../csv_files/final_data.csv", '../csv_files/final_data2.csv')
offers_filtered = pd.read_csv('../csv_files/final_data2.csv')
offers_filtered.head(5)

numeric_cols = offers_filtered.select_dtypes(include=[np.number]).columns.tolist()

numeric_cols = [col for col in numeric_cols if col not in ['id']]

plt.figure(figsize=(12, 10))
corr = offers_filtered[numeric_cols].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt=".2f", cmap='coolwarm', center=0,
            annot_kws={"size": 10}, cbar_kws={"shrink": .8})
plt.title("Матрица корреляций", pad=20)
plt.xticks(rotation=45)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""**Цена:**

Сильно коррелирует с площадью (0.75) и количеством комнат (0.53). Это указывает на то, что более крупные и многокомнатные объекты, как правило, дороже. Умеренная корреляция с ценой за квадратный метр (0.42), что логично, так как цена напрямую зависит от стоимости квадратного метра. Вопреки ожиданиям слабая корреляция с расстоянием до метро (-0.11). Но согласно наблюдениям, умеренная отрицательная корреляция с расстоянием до центра (-0.45), т.е. чем меньше расстояние до центра, тем больше стоимость.

**Площадь:**

Высокая корреляция с количеством комнат (0.81), что ожидаемо, так как большое количество комнат обычно означает большую площадь.

**Этаж и количество этажей:**

Умеренная положительная корреляция между собой (0.64), что тоже вполне логично (чем больше в здании этажей, тем больше может быть этаж объекта).

**Расстояние до центра:**

Умеренная положительная корреляция с этажностью (0.30 и 0.44), так как в центре не строят высокие здания, из-за чего образовалась зависимость. Также небольшая с расстоянием до метро (0.29), так как в центре плотность расположения станций больше и, соответственно, среднее расстояние до ближайшей меньше, чем на окраинах. Умеренная отрицательная корреляция с ценой за метр (-0.49).

Логичнее вместо признака расстояния до метро использовать для предсказания признак расстояния до центра, так как он коррелирует с ценой за квартиру сильнее. Соответственно, тогда выгоднее вернуть те строки исходных данных, у которых не была указана ближайшая станция метро и посчитать расстояние до центра и у них. Таким образом, удастся сохранить часть данных для обучения.

Продолжение в файле "Вторичный анализ.ipynb".
Рассмотрим подробнее зависимость цены от расстояния до центра и сэкономим данные.
"""